groups:
  lowdepth: /maps/projects/bos/people/wlk579/Banteng_project/3.sites_filtering/samplesbased_genolikes/depth/Waterbuffalo.CoverageBelow6x.16inds.bamlist
  highdepth: /maps/projects/bos/people/wlk579/Banteng_project/3.sites_filtering/samplesbased_genolikes/depth/Waterbuffalo.CoverageAbove6x.85inds.bamlist
outmain: results
chroms: /maps/projects/bos/people/wlk579/Banteng_project/3.sites_filtering/water_buffalo.reference.fna.fai.autosomes.list
angsdparams:
  maxdepth: 5000
  minQ: 30
  minMapQ: 25
allbed: /maps/projects/bos/people/wlk579/Banteng_project/3.sites_filtering/water_buffalo.reference.fna.fai.autosomes.bed
